# Generated by Django 4.0.2 on 2022-02-14 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мода')),
            ],
            options={
                'verbose_name': 'Мод',
                'verbose_name_plural': 'Моды',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сервера')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items_img/', verbose_name='Изображение предмета')),
                ('minimum_price', models.IntegerField(verbose_name='Минимальная стоимость')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='minimum_prices.mod', verbose_name='Мод')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='minimum_prices.server', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ('server', 'mod', 'name'),
            },
        ),
    ]
