# Generated by Django 4.0.2 on 2022-02-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimum_prices', '0002_mod_servers'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='item',
            name='minimum_price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
    ]
